/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:dd04cdeb-62a7-4219-bc2a-1505288affb2",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_zxAJCBcw3",
    "aws_user_pools_web_client_id": "66l1318feb4np7biljmv15ovch",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://5vggs4zkbndsva6asyamcoabpi.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-6zlnmhcmmrczbdkabmoysbh32m",
    "aws_user_files_s3_bucket": "myamplifybucket230413-dev",
    "aws_user_files_s3_bucket_region": "ap-southeast-1"
};


export default awsmobile;
